version: '3.3'

services:
  warehouse:
    container_name: warehouse
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8084'
    expose:
      - '8084'
    #restart: on-failure
    depends_on:
      - warehouse-db
  warehouse-db:
    container_name: warehouse-db
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      warehouse-net:
    environment:
      POSTGRES_DB: db-warehouse
      POSTGRES_PASSWORD: 123456

# Names our volume
volumes:
  wh-db:

networks:
  warehouse-net: