version: '3.3'

services:
  warehouse-db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_DB: db-warehouse
      POSTGRES_PASSWORD: 123456
  warehouse:
    container_name: warehouse
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - '8080:8084'
    # restart: on-failure
    #depends_on:
    #  - warehouse-db



# Names our volume
volumes:
  wh-db:

networks:
  backend: