version: '3.9'

services:
  product-db:
    container_name: product-db
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_DB: product-db
      POSTGRES_PASSWORD: 123456
  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    networks:
      - backend
      - database
    ports:
      - '8084:8084'
    # restart: on-failure
    depends_on:
      - product-db



# Names our volume
volumes:
  wh-db:

networks:
  backend:
    external: true
  database:
    external: true

